### ISSUE TITLE
#19# 扫描图书成功之后，提示“[-1]: 网络异常”

### ISSUE THREAD

**Issue by vincent4j** [eoecn/google_android_book_v2#2]
**现象**
扫描完图书，返回到App主界面，并提示：`[-1]: 网络异常`

**log**

```
06-04 19:42:35.575: V/BookSearcher(6074): download from: https://api.douban.com/v2/book/isbn/79417531464112233
06-04 19:42:36.005: D/dalvikvm(6074): GC_CONCURRENT freed 193K, 3% free 8955K/9180K, paused 8ms+5ms, total 52ms
06-04 19:42:36.336: V/BookSearcher(6074): The content of Book: <html><head><title>500 Internal Server Error</title></head><body bgcolor="white"><center><h1>500 Internal Server Error</h1></center><hr><center>nginx</center></body></html>
06-04 19:42:36.336: W/System.err(6074): org.json.JSONException: Value <html><head><title>500 of type java.lang.String cannot be converted to JSONObject
06-04 19:42:36.336: W/System.err(6074):     at org.json.JSON.typeMismatch(JSON.java:111)
06-04 19:42:36.346: W/System.err(6074):     at org.json.JSONObject.<init>(JSONObject.java:158)
06-04 19:42:36.346: W/System.err(6074):     at org.json.JSONObject.<init>(JSONObject.java:171)
06-04 19:42:36.346: W/System.err(6074):     at com.eoeandroid.booksearcher.Utils.download(Utils.java:38)
06-04 19:42:36.346: W/System.err(6074):     at com.eoeandroid.booksearcher.MainActivity$DownloadThread.run(MainActivity.java:127)
```

**原因**
当初写书之时，`HttpClient client = new DefaultHttpClient()`就可以通过；于是，就没有去对https协议进行处理。

当下，应该是豆瓣API对处理方式进行修改，必须设置https对应参数才行。

**修正记录**
- Pull Request: https://github.com/eoecn/google_android_book_v2/pull/1
- 变更点：https://github.com/vincent4j/google_android_book_v2/commit/b9f13a868582bfae7bb4fed263f0bf777ac0e89e

**Comment by vincent4j** [comment]
只需更新GitHub上的源码即可，书本中并未引用到此段代码。

**Comment by IceskYsl** [comment]
√
